# =========================================================
# ¡Hola Equipo Tenpo, bienvenidos a la Transaction API! 🚀
# Este archivo contiene la configuracion pertinente al backend de Java
# =========================================================

app:
  tenpo:
    max-transactions-per-user: 100
    rate-limiter:
      max-petitions-per-user: 3
      max-petitions-time-frame: 1
      refill-petitions-per-user: 3
spring:
  application:
    name: transaction-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mi_basededatos}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: tenpo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: tenpo
        dialect: org.hibernate.dialect.PostgreSQLDialect
