
services:
  database:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mi_basededatos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: neuralgoods/transaction-api:latest  # Usa la imagen subida a Docker Hub
    build: 
      context: ./transaction-api
      dockerfile: Dockerfile
    container_name: transaction-api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: mi_basededatos
      DB_USER: admin
      DB_PASSWORD: admin123

  frontend:
    image: neuralgoods/tenpo-frontend:latest  # Usa la imagen subida a Docker Hub
    build: 
      context: ./tenpo-transaction-frt
      dockerfile: Dockerfile
    container_name: tenpo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
