export const optionTabsArray = [
  {
    id: "0",
    optionName: "Buscar",
    textMainButton: "Buscar Transacción",
    showTransactionId: true,
    showSearchByTenpista: false,
    isFullFormTab: false,
    isEditing: false,
    canShowUpdate: true,
    canShowTable: true,
    canShowJson: true,
  },
  {
    id: "1",
    optionName: "Buscar por Tenpista",
    textMainButton: "Buscar por Tenpista",
    showTransactionId: false,
    showSearchByTenpista: true,
    isFullFormTab: false,
    isEditing: false,
    canShowUpdate: false,
    canShowTable: true,
    canShowJson: false,
  },
  {
    id: "2",
    optionName: "Crear",
    textMainButton: "Crear Transacción",
    showTransactionId: false,
    showSearchByTenpista: true,
    isFullFormTab: true,
    isEditing: false,
    canShowUpdate: false,
    canShowTable: true,
    canShowJson: true,
  },
  {
    id: "3",
    optionName: "Actualizar",
    textMainButton: "Actualizar Transacción",
    showTransactionId: true,
    showSearchByTenpista: true,
    isFullFormTab: true,
    isEditing: true,
    canShowUpdate: false,
    canShowTable: true,
    canShowJson: true,
  },
  {
    id: "4",
    optionName: "Eliminar",
    textMainButton: "Eliminar Transacción",
    showTransactionId: true,
    showSearchByTenpista: false,
    isFullFormTab: false,
    isEditing: false,
    canShowUpdate: false,
    canShowTable: false,
    canShowJson: true,
  },
];
