-- Crear esquema si no existe
CREATE SCHEMA IF NOT EXISTS tenpo;

-- Eliminar tablas y secuencias si existen
DROP TABLE IF EXISTS tenpo.transactions CASCADE;
DROP SEQUENCE IF EXISTS tenpo.transactions_seq;

-- Crear secuencia
CREATE SEQUENCE tenpo.transactions_seq START WITH 1 INCREMENT BY 1;

-- Crear la tabla transactions
CREATE TABLE tenpo.transactions (
    total_amount INTEGER,
    transaction_id INTEGER NOT NULL,
    transaction_date TIMESTAMP(6) WITH TIME ZONE,
    commerce VARCHAR(100),
    user_name VARCHAR(30),
    PRIMARY KEY (transaction_id)
);

CREATE INDEX idx_user_name_lower ON tenpo.transactions (LOWER(user_name));

-- Insertar datos de prueba
INSERT INTO tenpo.transactions (transaction_id, total_amount, commerce, user_name, transaction_date)
VALUES
(nextval('tenpo.transactions_seq'), 500, 'starbucks', 'johndoe', '2025-01-08 09:30:00'),
(nextval('tenpo.transactions_seq'), 1800, 'amazon', 'janedoe', '2025-01-08 10:15:00'),
(nextval('tenpo.transactions_seq'), 2300, 'apple', 'johndoe', '2025-01-08 11:00:00'),
(nextval('tenpo.transactions_seq'), 1000, 'google store', 'mike87', '2025-01-07 13:45:00'),
(nextval('tenpo.transactions_seq'), 2500, 'ebay', 'sarah95', '2025-01-07 14:30:00'),
(nextval('tenpo.transactions_seq'), 400, 'mcdonalds', 'johndoe', '2025-01-07 15:00:00'),
(nextval('tenpo.transactions_seq'), 3000, 'nike', 'annsmith', '2025-01-06 17:30:00'),
(nextval('tenpo.transactions_seq'), 800, 'bestbuy', 'mike87', '2025-01-06 19:00:00'),
(nextval('tenpo.transactions_seq'), 1200, 'walmart', 'janedoe', '2025-01-08 08:00:00'),
(nextval('tenpo.transactions_seq'), 1500, 'target', 'sarah95', '2025-01-08 12:00:00');


INSERT INTO tenpo.transactions (transaction_id, total_amount, commerce, user_name, transaction_date) VALUES
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 1),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 2),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 3),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 4),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 5),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 6),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 7),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 8),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 9),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 10),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 11),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 12),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 13),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 14),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 15),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 16),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 17),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 18),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 19),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 20),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 21),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 22),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 23),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 24),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 25),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 26),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 27),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 28),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 29),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 30),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 31),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 32),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 33),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 34),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 35),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 36),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 37),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 38),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 39),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 40),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 41),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 42),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 43),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 44),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 45),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 46),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 47),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 23),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 24),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 25),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 26),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 27),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 28),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 29),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 30),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 31),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 32),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 33),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 34),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 35),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 36),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 37),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 38),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 39),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 40),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 41),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 42),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 43),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 44),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 45),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 46),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 47),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 30),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 31),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 32),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 33),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 34),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 35),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 36),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 37),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 38),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 39),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 40),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 41),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 42),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 43),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 44),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 45),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 46),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 47),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 30),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 31),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 32),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 33),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'nike', 'alisonmandel', CURRENT_DATE - 34),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'walmart', 'alisonmandel', CURRENT_DATE - 35),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'amazon', 'alisonmandel', CURRENT_DATE - 36),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'starbucks', 'alisonmandel', CURRENT_DATE - 37),
(nextval('tenpo.transactions_seq'), (RANDOM() * (5000 - 100) + 100)::INTEGER, 'ebay', 'alisonmandel', CURRENT_DATE - 38);
